name: echo

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    types: [opened]
  pull_request_review:
    branches:
      - master
      - develop
    types: [submitted]

jobs:
  echo:
    if: github.event.workflow_run.event == 'workflow_dispatch' || github.event.pull_request.opened || github.event.pull_request_review.approved
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello, world!"
